### ISSUE TITLE
Indentation issue.

### ISSUE THREAD

**Issue by LucasMaliszewski** [Dickurt/vscode-php-formatter#11]
The one issues I've seen and cannot use due to the abnormal indentation that occurs. 

# Before
```PHP
	/**
	 * @return mixed
         */
        public function getFile() {
            return $this->file;
	}
```
# After
```PHP
	/**
	* @return mixed
	     */
	    public function getFile() {
		return $this->file;
	}
```

**Comment by Dickurt** [comment]
So this is after you run the formatter? Could you perhaps turn on logging (by setting `phpformatter.logging = true` in your settings) and post the console logs here? I'm curious as to what might go wrong.

Also check out the [Troubleshooting](https://github.com/Dickurt/vscode-php-formatter/wiki/Troubleshooting) section on the wiki, it will provide some insight into what might cause your issue.

**Comment by vysker** [comment]
Assuming this has been fixed. Closing for now.
