### ISSUE TITLE
unworkable with default arguments setting

### ISSUE THREAD

**Issue by Ult-UX** [Dickurt/vscode-php-formatter#13]
```
    // Add arguments to the executed fix command, like so: ['--level=psr2', '--fixers=linefeed,short_tag,indentation'].
    "phpformatter.arguments": [
        "--level=psr2"
    ],
```
Console
>   The "--level" option does not exist.

**Comment by Dickurt** [comment]
PHP CS Fixer recently released an update. The `--level` argument has been renamed to `--rules`. More details can be found [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/f3baf72eb2f58bf275b372540f5b47d25aed910f/UPGRADE.md#cli-options).

**Comment by Dickurt** [comment]
Closed this because there has been no response and I believe this should be the proper fix.
