### ISSUE TITLE
add a new block line when format selected lines

### ISSUE THREAD

**Issue by stonyz** [Dickurt/vscode-php-formatter#14]
**Steps**,
1. Select some lines, 
2. and format it by shift+alt+F  
2. wait about 1s  (This is also an issue, cann't format immediatly, must wait about 1 second)

**Result**,
An additional new line was added to the tail of the selected code section.

If press shift+alt+F   again, one more blank line will be added again.

**Comment by Dickurt** [comment]
Hello Stonyz,

Have you tried any of the [fixers](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/README.rst) to solve this? Try `no_trailing_whitespace`, for instance. If that doesn't work, try other fixers that revolve around things like hitespace.

Let me know if any of those work.

**Comment by vysker** [comment]
Assuming this has been fixed. Closing for now.
