### ISSUE TITLE
Feature request: format using regular shortcut instead of onSave

### ISSUE THREAD

**Issue by websquared** [Dickurt/vscode-php-formatter#2]
Hi, great extension. But would be good to have an option to format only specific files, not all of them on save, using regular ALT-SHIFT-F shortcut.

I'm not an expert in VScode plugins but I think it could be done using registerDocumentFormattingEditProvider function like here: https://github.com/guodf/VSCode-phpfmt/blob/master/extension.js#L49

**Comment by Dickurt** [comment]
Thanks for opening this issue. This feature has just now been introduced in 0.1.0. You can find out how to set this up [here](https://github.com/Dickurt/vscode-php-formatter#extension-commands).
