### ISSUE TITLE
Extension does not work

### ISSUE THREAD

**Issue by enriquemorenotent** [Dickurt/vscode-php-formatter#27]
I am running Ubuntu 18.04 and Visual Studio Code 1.23

Composer is in my path:
```
$ which composer
/home/dbugger/.phpbrew/bin/composer
```
`php-cs-fixer` is also in my path:
```
$ which php-cs-fixer
/home/dbugger/.composer/vendor/bin/php-cs-fixer
```

This are my settings:
```
    ...
    "phpformatter.composer": true,
    "phpformatter.logging": true,
    "phpformatter.arguments": ["--rules=@PSR2"],
    "phpformatter.notifications": true,
    ....
```

If I actually use `php-cs-fix` in my terminal, **it does work**. But when I try to make it work on vscode, I get no output

I even did a KeyBinding to test it.

![image](https://user-images.githubusercontent.com/368842/41295893-eaa09b48-6e5b-11e8-919a-66448f9d9964.png)

What could be missing?

**UPDATE** I forgot to say, that I installed vscode through a snap package, in case it is relevant

**Comment by wbovela** [comment]
Exactly the same problem but running on MacOs High Sierra (10.13.5) and Visual Studio Code 1.24.1.
php-cs-fixer works fine from the command line, but the extension will not work in VSC. 
No output in the Debug Console, despite phpformatter.logging set to true. No notifications either.

**Comment by caseybecking** [comment]
Same issue here - MacOs High Sierra - installed via brew. Even tried to tell it `pharPath":"/usr/local/Cellar/php-cs-fixer/2.12.2/bin/php-cs-fixer"` Still no go.

**Comment by AlecRobertson** [comment]
Try adding `"phpformatter.arguments": []` to your Visual Studio Code's User Settings.

**Comment by enriquemorenotent** [comment]
I have left my PHP project, so I will not be checking on this issue anymore, but I will leave it open, as it seems other users are having it too.

**Comment by sgehrman** [comment]
Why isn't "phpformatter.arguments": [] part of your simple instructions?  Spent an hour trying to get this working. I'm on Linux.
