### ISSUE TITLE
formatting on save

### ISSUE THREAD

**Issue by DXkite** [Dickurt/vscode-php-formatter#4]
when set onSave is true, i save some file, the file formatted, but file status is "change" i need to save again,**Then Formatting Again And Again....**
![screengif](https://cloud.githubusercontent.com/assets/7450707/18626320/e02f7178-7e86-11e6-9063-d5141798f58d.gif)

**Comment by Dickurt** [comment]
Thanks for taking the time to open this issue.

Unfortunately there is no fix for this as of now. Microsoft is [working on a preSave event](https://github.com/Microsoft/vscode/issues/239) for VSCode, which would prevent this issue from cropping up. It is currently in the backlog of the September milestone.

For now, you can work around this issue by [creating a custom command that triggers this extension's fix functionality](https://github.com/Dickurt/vscode-php-formatter#phpformatterfix).

In order to avoid future confusion, I will add this to the extension's docs and readme.

**Comment by DXkite** [comment]
You can add Format Code to Right click menu like  Native Command `Ctrl+F`
![qq 20160919174336](https://cloud.githubusercontent.com/assets/7450707/18627999/a281f436-7e90-11e6-86c4-554cebfe208d.png)

**Comment by Dickurt** [comment]
That's a great suggestion. Do you happen to know how the `when` condition should be setup to allow file extensions other than php?

I'm trying something like this:

```
"contributes": {
    "commands": [
      {
        "command": "phpformatter.fix",
        "title": "Format PHP",
        "icon": {
          "light": "./images/fix-icon-light.svg",
          "dark": "./images/fix-icon-dark.svg"
        }
      }
    ],
    "menus": {
      "editor/context": [
        {
          "when": "resourceLangId == php || vscode.workspace.getConfiguration('phpformatter').get('additionalExtensions', []).indexOf(resourceLangId) > -1",
          "command": "phpformatter.fix"
        }
      ]
    }
}
```

**Comment by DXkite** [comment]
htm* or  tpl  ?

**Comment by DXkite** [comment]
You Can  add  a  item like `Format As  PHP` when  The Extension may has Php code,Or Just Use  in php  file, another file  needn`t  Format  such as  in  html or  template :
` <title><?php  echo $title ; ?></title>`

**Comment by Dickurt** [comment]
Yes, that would indeed be unnecessary. However, what I meant is that it would be even less necessary to have the context menu item at all, it the current file is not a PHP file.

**Comment by DXkite** [comment]
Last Night,I  use PHP Function `token_get_all` to  Compile template file  ( Copy from  Laravel ) ,I guess  Maybe Can  use something like this?

**Comment by jrieken** [comment]
@Dickurt Since version 1.6 VS Code supports the `onWillSaveTextDocument`-event. Also there is a new `editor.formatOnSave`-setting that will invoke registered formatters on save, see #5

**Comment by Dickurt** [comment]
Resolved with conversion to TypeScript in latest milestone.
