### ISSUE TITLE
Add support to custom config file

### ISSUE THREAD

**Issue by pierophp** [Dickurt/vscode-php-formatter#8]
Hello,

Please, can you add support for custom config files?
With the "--config-file" flag you can use a custom .php_cs file.

Thanks

**Comment by Dickurt** [comment]
This will be added to the new milestone. Thanks for the suggestion!

For some reason I wasn't automatically notified of this issue. Sorry for the long wait.

**Comment by Dickurt** [comment]
I think I misread the question. Could you elaborate upon this feature? What does the custom config file do? Where do you put it? And how should it be linked?

**Comment by pierophp** [comment]
@Dickurt 

Here a ".php_cs" config file example:
https://gist.github.com/pierophp/8dbec133f4423bb8d7684911383a2f1b

I putted this file in the root of my project.

**Comment by pierophp** [comment]
Currently we use this command to run the fixer:

./vendor/bin/php-cs-fixer --config-file=./.php_cs fix my_file.php

**Comment by Dickurt** [comment]
Ah, I see what you're talking about now.

I propose we add an additional setting to the extension called `phpformatter.configFile` to point to such a file (with a path). The extension will then run the command with the necessary switch and point to the config file. Should be doable.

**Comment by pierophp** [comment]
I agree with the phpformatter.arguments option

**Comment by Dickurt** [comment]
The implementation is simple enough, there will just have to be some testing before committing it.

**Comment by Dickurt** [comment]
I added the feature in the latest version, it should be online any minute. Would you mind if I used the .php_cs file you provided as an example on the wiki?

**Comment by pierophp** [comment]
No problem!

**Comment by Dickurt** [comment]
Thanks! I'm closing this now as the feature has been implemented. If it does not work as advertised, or doesn't live up to the expectations, please open a new issue.
